### ISSUE TITLE
修复输出CSV文件 中文乱码问题

### ISSUE THREAD

**Issue by FengX1776** [badafans/Cloudflare-IP-SpeedTest#2]
使用后发现输出的CSV文件中顶头中文有乱码
修复方式为在CSV文件的开头中写入 UTF-8 BOM
在326行加入以下代码再编译即可

`file.WriteString("\xEF\xBB\xBF")`

**Comment by badafans** [comment]
这个影响不大吧，主要看系统默认编码的支持，一般来说linux下使用无障碍。
