### ISSUE TITLE
IP文件内容需要什么样的格式？

### ISSUE THREAD

**Issue by yutian81** [badafans/Cloudflare-IP-SpeedTest#6]
如果IP文件中的每个IP有指定的端口，那么软件支持什么样的格式？
假设有一个IP文件，其内容为：`38.207.129.85:51231`

这样的格式是否可以正常测速？

IP和端口如何组合才是软件所支持的格式？

是用`:`分隔还是用`,`分隔

支持这样的格式：`38.207.129.85:51231`

还是支持这样的格式：`38.207.129.85,51231`

或者是其他格式

请大佬解惑！

**Comment by badafans** [comment]
有单独的指定端口的版本，需要你自己编译一下。
ip.txt的文件格式为
47.243.161.235 2053
47.243.241.157 2053
47.240.31.5  2083
8.210.55.134 2083

下载zip压缩文件，里面有个iptest.go 你自己编译一下就行
[iptest.zip](https://github.com/user-attachments/files/16361256/iptest.zip)

**Comment by yutian81** [comment]
谢谢大佬
